# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["dmilitaru@fastly.com", "kblanks@fastly.com"]
description = "A low quality image placeholder (LQIP) generator, using Fastly's Compute@Edge"
language = "rust"
manifest_version = 3
name = "edge-lqip"
service_id = "4JtgxbHDuyoBr978SvR2BT"

[local_server]
  [local_server.backends]
    [local_server.backends.content_backend]
      url = "https://images.unsplash.com"

[setup]
  [setup.backends]
    [setup.backends.content_backend]
      address = "images.unsplash.com"
      port = 443
